version: "3.8"
services:
  postgres_db:
    image: postgres:15.3-alpine3.18
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-docker}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-1234}
      POSTGRES_DB: ${POSTGRES_DB:-pharma}
      PGDATA: /data/postgres
    volumes:
      - type: volume
        source: postgres_data
        target: /data/postgres
        volume:
          nocopy: true
    ports:
      - "5432:5432"
volumes:
  postgres_data:
    external: true
    name: pharma_data