spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_DATABASE:pharma}
    username: ${DB_USERNAME:docker}
    password: ${DB_PASSWD:1234}
    driverClassName: org.postgresql.Driver
  jpa:
    showSql: true
    properties:
      jdbc:
        timeZone: UTC
      hibernate:
        formatSql: true
    hibernate:
      ddlAuto: validate
pharma:
  jwt:
    secret: ${PHARMA_JWT_SECRET:1234}
    issuer: ${PHARMA_JWT_ISSUER:example}
    accessTokenExpirationInMin: 60
    refreshTokenExpirationInMin: 43830
  upload:
    sessions:
      - type: medicine_preview
        maximumFileCount: 5
        expiredDurationInMin: 60
    local: true
server:
  port: 8080
  servlet:
    contextPath: /api/v1