spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_DATABASE:pharma}
    username: ${DB_USERNAME:docker}
    password: ${DB_PASSWD:1234}
    driverClassName: org.postgresql.Driver
  jpa:
    showSql: true
    properties:
      jdbc:
        timeZone: UTC
      hibernate:
        formatSql: true
    hibernate:
      ddlAuto: validate
  servlet:
    multipart:
      maxFileSize: -1
      maxRequestSize: -1
pharma:
  applicationUrl: ${PHARMA_AUTH_APPLICATION_URL:http://localhost:3000}
  jwt:
    secret: ${PHARMA_JWT_SECRET:1234}
    issuer: ${PHARMA_JWT_ISSUER:example}
    accessTokenExpirationInMin: 60
    refreshTokenExpirationInMin: 43830
  oauth2:
    google:
      clientId: ${PHARMA_AUTH_GOOGLE_CLIENT_ID}
      clientSecret: ${PHARMA_AUTH_GOOGLE_CLIENT_SECRET}
    facebook:
      clientId: ${PHARMA_AUTH_FACEBOOK_CLIENT_ID}
      clientSecret: ${PHARMA_AUTH_FACEBOOK_CLIENT_SECRET}
  upload:
    sessions:
      - type: medicine_preview
        maximumFileCount: 5
        expiredDurationInMin: 60
        prefix: ./uploaded/medicine_preview
    local: true
  order:
    expiredDurationInDays: 3
server:
  port: 8888
  servlet:
    contextPath: /api/v1